### ISSUE TITLE
Configurable 2.1.1 Crash on Launch, 2.0.3 Work Fine

### ISSUE THREAD

**Issue by Horizoll** [Bawnorton/Configurable#5]
Launched With:

All the Trims 5.0.1
Better Trims 3.2.8
Dynamic Trim 2.0.0
Runtime Trims 1.0.4

[crash-2024-10-21_03.05.19-client.txt](https://github.com/user-attachments/files/17452183/crash-2024-10-21_03.05.19-client.txt)

**Comment by Bawnorton** [comment]
Should be fixed in 2.1.2
