### ISSUE TITLE
Crash due to this mod?

### ISSUE THREAD

**Issue by VaporeonScripts** [Bawnorton/Configurable#7]
Neoforge 1.21.1 https://mclo.gs/ZLfAkwb

**Comment by Bawnorton** [comment]
God damn windows and using `\` as their file separator unlike a normal operating system

**Comment by VaporeonScripts** [comment]
I agree,linux on top

**Comment by Bawnorton** [comment]
Try this https://maven.bawnorton.com/releases/com/bawnorton/configurable/configurable-neoforge-yarn/2.1.3+1.21.1/configurable-neoforge-yarn-2.1.3+1.21.1.jar

**Comment by VaporeonScripts** [comment]
Sent it to the guy,ima wait for results

**Comment by VaporeonScripts** [comment]
Works
