### ISSUE TITLE
the library doesnt work on hosted server (neoforge 1.21.1)

### ISSUE THREAD

**Issue by VaporeonScripts** [Bawnorton/Configurable#8]
Configurable (configurable) has failed to load correctly
          java.lang.ExceptionInInitializerError: null

**Comment by Bawnorton** [comment]
Logs?

**Comment by VaporeonScripts** [comment]
yes,give me a second xd

**Comment by VaporeonScripts** [comment]
https://mclo.gs/RfwgBR1

**Comment by Bawnorton** [comment]
There's some weird interaction going on with forge's patch loader and configurable. This shouldn't crash normally but forge has injected some code into one of RuntimeTrims classes causing it to crash

**Comment by Bawnorton** [comment]
Update RT to 1.0.5 and Configurable to 2.2.0. Should fix the issue; close if so

**Comment by VaporeonScripts** [comment]
I'll see tomorrow

**Comment by VaporeonScripts** [comment]
fixed all issues,servers works fine, ty for fixing the issues

**Comment by VaporeonScripts** [comment]
oh lmao wrong thread
