### ISSUE TITLE
crash neoforge 1.21.1

### ISSUE THREAD

**Issue by VaporeonScripts** [Bawnorton/Configurable#9]
https://mclo.gs/DxBvcJH

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/4fe7fec4-5606-485d-aed3-4292543228c7)

**Comment by Bawnorton** [comment]
And now a NeoForge update has broken FFAPI. I am slowly losing my mind

**Comment by VaporeonScripts** [comment]
same

**Comment by Bawnorton** [comment]
Pulled the FFAPI dep out of configurable so now it is decoupled from the neoforge version it built with to avoid this kind of issue. You'll need FFAPI as a separate dep now unfortunately, but this is fixed in 2.2.1

**Comment by VaporeonScripts** [comment]
wtf is ffapi

**Comment by VaporeonScripts** [comment]
if u meant forgified fabric api, no worries, im using it already to be able to use continuity(fabric) and fish of thieves (needs it for neoforge apparently)

**Comment by Bawnorton** [comment]
Yeah, close if it no longer crashes

**Comment by VaporeonScripts** [comment]
ima see that right now!

**Comment by VaporeonScripts** [comment]
doesnt show that issue anymore, altough now i got diff issue breh

**Comment by VaporeonScripts** [comment]
https://mclo.gs/jzNKX5O idk if this regards u or idk

**Comment by Bawnorton** [comment]
I don't think so

**Comment by VaporeonScripts** [comment]
packet fixer was missing, it works now, but new error, ima troubleshoot it
